### ISSUE TITLE
Putting Tags on 1.x Issues

### ISSUE THREAD

**Issue by dfockler** [resque/resque#1321]
It looks like a lot of the issues for this project are on the 1.x branch. Is 1.x still being maintained? If not it would be useful to tag issues as being on 1.x. I'd love to start digging into some issues for this project, it's just hard to know where to start or what is being worked on.

Thanks

**Comment by yaauie** [comment]
As `master` has diverged fairly significantly without a release, issues against 1-x-stable are actually the only thing I'm really interested in spending time on, so I would find this useful.

In terms of "maintained", well, that implies "maintainers", and while there are several of us with commit bits, all of us do it in our own time without any dedicated resources (e.g., funding), so maintenance of this project tends to come secondary to employment, health, and family commitments. If there are outstanding issues that need attention, I do have some limited bandwidth to help, but it may take some extra effort on your part to get (and keep) my attention :smile:

**Comment by yaauie** [comment]
Closing this ticket, as I believe the issue was resolved by my previous answer.

**Comment by dfockler** [comment]
Thanks for the reply. I realize this is a 'work on it when you can' sort of project at this point. I still see quite a few people around using Resque, but I guess the project is pretty stable at this point, so there aren't that many show stopping issues. If I notice something I can fix on 1-x-stable, I'll try and send it in.
