### ISSUE TITLE
Error running resque-web: cannot load such file -- rack/showexceptions

### ISSUE THREAD

**Issue by troelskn** [resque/resque#1436]
This is a bug report + solution in one. I'm posting in case someone else is running into the same problems as I was.

I was getting this rather cryptic error, trying to invoke `resque-web`:

```
$ resque-web -p 8282 config/initializers/resque.rb
/Users/troelskn/.rvm/gems/ruby-2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require': cannot load such file -- rack/showexceptions (LoadError)
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `<top (required)>'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `require'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/sinatra-1.0/lib/sinatra/base.rb:6:in `<top (required)>'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/resque-1.26.0/lib/resque/server.rb:1:in `require'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/resque-1.26.0/lib/resque/server.rb:1:in `<top (required)>'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/resque-1.26.0/bin/resque-web:10:in `require'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/gems/resque-1.26.0/bin/resque-web:10:in `<top (required)>'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/bin/resque-web:23:in `load'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/bin/resque-web:23:in `<main>'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/troelskn/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

There is a hint in that sinatra 1.0 is loaded, even though I have the latest (1.4.7) installed. I did some digging, and Sinatra 1.0 is the newest version that doesn't depend on a rack 1.x. Since I have rack 2.x installed, this gives incompatibility issues. So the fix is to use edge Sinatra, which relies on rack 2. To do so, I had to add sinatra to my Gemfile:

```
gem 'resque'
gem 'sinatra', github: 'sinatra/sinatra', branch: 'master'
```

Of course, once a version of Sinatra that depends on rack 2.x is released, this will become a non-issue. But till then, hope this helps someone.

**Comment by naidevcodes** [comment]
This didnt work for me.

**Comment by k2m30** [comment]
Neither for me

http://stackoverflow.com/questions/36605755/how-to-make-a-gem-work-with-newer-version-of-dependencies

Here is suggested to make a fork and change dependency. Not sure if I want to deal with it.

**Comment by k2m30** [comment]
gem 'sinatra', github: 'sinatra/sinatra', branch: 'master'
sinatra was resolved to 2.0.0.pre.alpha, which depends on
      rack (= 2.0.0.rc1)

**Comment by bird1235456** [comment]
Using Ruby 5.0 I am getting this error

/.rvm/gems/ruby-2.3.0/gems/sinatra-1.0/lib/sinatra/showexceptions.rb:1:in `require': cannot load such file -- rack/showexceptions (LoadError)

**Comment by mbostler** [comment]
Confirming that adding `gem 'sinatra', github: 'sinatra/sinatra', branch: 'master'` in my Gemfile fixed this for me.

This is using rails 5.0.1 and resque 1.27.1

Before I was getting a `activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require': cannot load such file -- rack/showexceptions (LoadError)` when trying to run "rails server"

**Comment by bird1235456** [comment]
I get this?

gem install 'sinatra', github: 'sinatra/sinatra', branch: 'master'

ERROR:  Could not find a valid gem 'sinatra,' (>= 0) in any repository

ERROR:  Possible alternatives: sinatras, sinatra, sinatra-dm, siatra,
ginatra

ERROR:  Could not find a valid gem 'github:' (>= 0) in any repository

ERROR:  Possible alternatives: github, git_hub, git-hub, github-pr,
github-tv

ERROR:  Could not find a valid gem 'sinatra/sinatra,' (>= 0) in any
repository

ERROR:  Possible alternatives: sinatra-sinatra, sinatra-strap,
sinatra-json_rpc, sinatra-jsonapi, sinatra-paginate

ERROR:  Could not find a valid gem 'branch:' (>= 0) in any repository

ERROR:  Possible alternatives: branch, branchy, branch_io, brancher,
branches

ERROR:  Could not find a valid gem 'master' (>= 0) in any repository

ERROR:  Possible alternatives: easter, aster, faster, mister, mastar

**Comment by bird1235456** [comment]
I've tried to install sinatra and resque, I bundle install. but they are
missing on my bundle show? Here is my gem list

Successfully installed sinatra-1.4.8

Parsing documentation for sinatra-1.4.8

Done installing documentation for sinatra after 0 seconds

1 gem installed

Marks-MacBook-Pro:comdevsunion markstumbris$ bundle install

Using rake 12.0.0

Using concurrent-ruby 1.0.4

Using i18n 0.8.0

Using minitest 5.10.1

Using thread_safe 0.3.5

Using builder 3.2.3

Using erubis 2.7.0

Using mini_portile2 2.1.0

Using rack 2.0.1

Using nio4r 1.2.1

Using websocket-extensions 0.1.2

Using mime-types-data 3.2016.0521

Using arel 7.1.4

Using execjs 2.7.0

Using sass 3.4.23

Using byebug 9.0.6

Using coffee-script-source 1.12.2

Using method_source 0.8.2

Using thor 0.19.4

Using debug_inspector 0.0.2

Using ffi 1.9.17

Using multi_json 1.12.1

Using rb-fsevent 0.9.8

Using puma 3.7.0

Using bundler 1.14.4

Using tilt 2.0.6

Using sqlite3 1.3.13

Using turbolinks-source 5.0.0

Using will_paginate 3.1.5

Using tzinfo 1.2.2

Using nokogiri 1.7.0.1

Using rack-test 0.6.3

Using sprockets 3.7.1

Using websocket-driver 0.6.5

Using mime-types 3.1

Using autoprefixer-rails 6.7.3

Using uglifier 3.0.4

Using coffee-script 2.4.1

Using rb-inotify 0.9.8

Using turbolinks 5.0.1

Using activesupport 5.0.1

Using loofah 2.0.3

Using mail 2.6.4

Using bootstrap-sass 3.3.7

Using listen 3.0.8

Using rails-dom-testing 2.0.2

Using globalid 0.3.7

Using activemodel 5.0.1

Using jbuilder 2.6.1

Using spring 2.0.1

Using rails-html-sanitizer 1.0.3

Using activejob 5.0.1

Using activerecord 5.0.1

Using spring-watcher-listen 2.0.1

Using actionview 5.0.1

Using actionpack 5.0.1

Using actioncable 5.0.1

Using actionmailer 5.0.1

Using railties 5.0.1

Using sprockets-rails 3.2.0

Using coffee-rails 4.2.1

Using jquery-rails 4.2.2

Using web-console 3.4.0

Using rails 5.0.1

Using sass-rails 5.0.6

Bundle complete! 17 Gemfile dependencies, 65 gems now installed.

Use `bundle show [gemname]` to see where a bundled gem is installed.

Marks-MacBook-Pro:comdevsunion markstumbris$ bundle show

Gems included by the bundle:

  * actioncable (5.0.1)

  * actionmailer (5.0.1)

  * actionpack (5.0.1)

  * actionview (5.0.1)

  * activejob (5.0.1)

  * activemodel (5.0.1)

  * activerecord (5.0.1)

  * activesupport (5.0.1)

  * arel (7.1.4)

  * autoprefixer-rails (6.7.3)

  * bootstrap-sass (3.3.7)

  * builder (3.2.3)

  * bundler (1.14.4)

  * byebug (9.0.6)

  * coffee-rails (4.2.1)

  * coffee-script (2.4.1)

  * coffee-script-source (1.12.2)

  * concurrent-ruby (1.0.4)

  * debug_inspector (0.0.2)

  * erubis (2.7.0)

  * execjs (2.7.0)

  * ffi (1.9.17)

  * globalid (0.3.7)

  * i18n (0.8.0)

  * jbuilder (2.6.1)

  * jquery-rails (4.2.2)

  * listen (3.0.8)

  * loofah (2.0.3)

  * mail (2.6.4)

  * method_source (0.8.2)

  * mime-types (3.1)

  * mime-types-data (3.2016.0521)

  * mini_portile2 (2.1.0)

  * minitest (5.10.1)

  * multi_json (1.12.1)

  * nio4r (1.2.1)

  * nokogiri (1.7.0.1)

  * puma (3.7.0)

  * rack (2.0.1)

  * rack-test (0.6.3)

  * rails (5.0.1)

  * rails-dom-testing (2.0.2)

  * rails-html-sanitizer (1.0.3)

  * railties (5.0.1)

  * rake (12.0.0)

  * rb-fsevent (0.9.8)

  * rb-inotify (0.9.8)

  * sass (3.4.23)

  * sass-rails (5.0.6)

  * spring (2.0.1)

  * spring-watcher-listen (2.0.1)

  * sprockets (3.7.1)

  * sprockets-rails (3.2.0)

  * sqlite3 (1.3.13)

  * thor (0.19.4)

  * thread_safe (0.3.5)

  * tilt (2.0.6)

  * turbolinks (5.0.1)

  * turbolinks-source (5.0.0)

  * tzinfo (1.2.2)

  * uglifier (3.0.4)

  * web-console (3.4.0)

  * websocket-driver (0.6.5)

  * websocket-extensions (0.1.2)

  * will_paginate (3.1.5)

Marks-MacBook-Pro:comdevsunion markstumbris$ rails s -b 0.0.0.0

=> Booting Puma

=> Rails 5.0.1 application starting in development on http://0.0.0.0:3000

=> Run `rails server -h` for more startup options

Exiting

/Users/markstumbris/comdevsunion/config.ru:3:in `require_relative': cannot
load such file -- /Users/markstumbris/comdevsunion/config/environment
(LoadError)

**Comment by Ravenstine** [comment]
Installing Sinatra from master works for me, however, I'm still left with this causing my jobs to fail:
`cannot load such file -- rack/showexceptions`

Using Rails 5.0.2.  Still a problem even in a brand new project.

**Comment by anka** [comment]
Following configuration solved the problem on my project:
```
rails (5.0.2)
sinatra (2.0.0)
resque (1.27.4)
```

**Comment by dfabreguette-ap** [comment]
For the record, what solves the problem is the upgrade of sinatra to 2.0.0, just for info.
